In [1]:
# Import dependencies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
# Import CSV
index = pd.read_csv('data/basic_index/index_full.csv')
index

,Unnamed: 0,Name,Index Year,Overall Score,Property Rights,Government Integrity,Judicial Effectiveness,Tax Burden,Government Spending,Fiscal Health,Business Freedom,Labor Freedom,Monetary Freedom,Trade Freedom,Investment Freedom,Financial Freedom
0,0,Afghanistan,2003,59.61,48.6,39.52,NaN,71.40,67.66,NaN,63.03,NaN,75.85,64.15,53.44,52.87
1,1,Albania,2003,56.80,30.0,10.00,NaN,83.80,70.40,NaN,55.00,NaN,85.80,56.20,70.00,50.00
2,2,Algeria,2003,57.70,30.0,50.00,NaN,65.20,74.90,NaN,70.00,NaN,78.90,50.40,70.00,30.00
3,3,Angola,2003,59.61,48.6,39.52,NaN,71.40,67.66,NaN,63.03,NaN,75.85,64.15,53.44,52.87
4,4,Argentina,2003,56.30,30.0,35.00,NaN,72.20,76.80,NaN,70.00,NaN,88.50,54.00,50.00,30.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3129,3129,Venezuela,2019,25.90,7.6,7.90,13.1,74.70,58.10,17.6,33.90,28.0,0.00,60.00,0.00,10.00
3130,3130,Vietnam,2019,55.30,49.8,34.00,40.3,79.70,74.10,40.7,63.50,62.8,68.90,79.20,30.00,40.00
3131,3131,Yemen,2019,60.77,19.6,20.30,22.2,77.21,83.70,0.0,45.10,49.8,61.50,71.40,50.00,48.78
3132,3132,Zambia,2019,53.60,45.0,32.30,35.6,72.30,80.10,12.3,71.10,46.0,70.30,72.60,55.00,50.00
3133,3133,Zimbabwe,2019,40.40,29.7,15.80,24.8,62.30,74.50,23.7,33.40,43.3,72.40,70.00,25.00,10.00

In [3]:
# # Drop extra column
del index['Unnamed: 0']
index

,Name,Index Year,Overall Score,Property Rights,Government Integrity,Judicial Effectiveness,Tax Burden,Government Spending,Fiscal Health,Business Freedom,Labor Freedom,Monetary Freedom,Trade Freedom,Investment Freedom,Financial Freedom
0,Afghanistan,2003,59.61,48.6,39.52,NaN,71.40,67.66,NaN,63.03,NaN,75.85,64.15,53.44,52.87
1,Albania,2003,56.80,30.0,10.00,NaN,83.80,70.40,NaN,55.00,NaN,85.80,56.20,70.00,50.00
2,Algeria,2003,57.70,30.0,50.00,NaN,65.20,74.90,NaN,70.00,NaN,78.90,50.40,70.00,30.00
3,Angola,2003,59.61,48.6,39.52,NaN,71.40,67.66,NaN,63.03,NaN,75.85,64.15,53.44,52.87
4,Argentina,2003,56.30,30.0,35.00,NaN,72.20,76.80,NaN,70.00,NaN,88.50,54.00,50.00,30.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3129,Venezuela,2019,25.90,7.6,7.90,13.1,74.70,58.10,17.6,33.90,28.0,0.00,60.00,0.00,10.00
3130,Vietnam,2019,55.30,49.8,34.00,40.3,79.70,74.10,40.7,63.50,62.8,68.90,79.20,30.00,40.00
3131,Yemen,2019,60.77,19.6,20.30,22.2,77.21,83.70,0.0,45.10,49.8,61.50,71.40,50.00,48.78
3132,Zambia,2019,53.60,45.0,32.30,35.6,72.30,80.10,12.3,71.10,46.0,70.30,72.60,55.00,50.00
3133,Zimbabwe,2019,40.40,29.7,15.80,24.8,62.30,74.50,23.7,33.40,43.3,72.40,70.00,25.00,10.00

In [4]:
# Creating a dict of dataframes, separated by each country
unique_country = index.Name.unique()

country_dict_df = {elem : pd.DataFrame() for elem in unique_country}
country_dict_df

for key in country_dict_df.keys():
    country_dict_df[key] = index[:][index.Name == key]