In [1]:
# Import dependencies
import pandas as pd
import numpy as np

In [2]:
# Import CSV File
file = 'data/master_index2019_data.csv'

In [3]:
# Read csv into pandas
df = pd.read_csv(file, encoding="ISO-8859-1")

In [5]:
# Identify imcomplete rows
df.count()

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,71.0,Hong Kong,HongKong,Asia-Pacific,1.0,1.0,90.2,93.3,75.3,83.8,...,Hong Kong SAR,7.4,$454.9,3.8,2.8,"$61,393",3.1,1.5,"104,333.0",0.1
1,147.0,Singapore,Singapore,Asia-Pacific,2.0,2.0,89.4,97.4,92.4,95.1,...,Singapore,5.6,$527.0,3.6,3.5,"$93,906",2.0,0.6,"62,006.0",110.9
2,120.0,New Zealand,NewZealand,Asia-Pacific,3.0,3.0,84.4,95.0,83.5,96.7,...,New Zealand,4.8,$188.6,3.0,3.3,"$38,934",4.9,1.9,"3,572.0",26.4
3,158.0,Switzerland,Switzerland,Europe,4.0,1.0,81.9,85.3,82.0,88.0,...,Switzerland,8.4,$517.2,1.1,1.6,"$61,422",4.8,0.5,"40,986.1",42.8
4,7.0,Australia,Australia,Asia-Pacific,5.0,4.0,80.9,79.1,86.5,79.9,...,Australia,24.8,"$1,246.5",2.3,2.4,"$50,334",5.6,2.0,"46,368.0",41.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,97.0,Liechtenstein,Liechtenstein,Europe,NaN,NaN,NaN,NaN,NaN,NaN,...,Liechtenstein,"38,000 ppl.",$6.1 CHF (2014 ),NaN,NaN,"$139,100 (2009 est.)",2.1 (2016),NaN,NaN,NaN
183,184.0,Somalia,Somalia,Sub-Saharan Africa,NaN,NaN,NaN,33.7,26.6,7.9,...,Somalia,14.3,$18.70,1.8,2.2,NaN,6.0,NaN,384.0,NaN
184,159.0,Syria,Syria,Middle East and North Africa,NaN,NaN,NaN,37.0,24.4,20.3,...,Syria,18.4,NaN,NaN,NaN,NaN,14.9,NaN,NaN,NaN
185,181.0,Yemen,Yemen,Middle East and North Africa,NaN,NaN,NaN,19.6,22.2,20.3,...,Yemen,30.0,$38.6,-13.8,-16.1,"$1,287",14.0,4.9,-269.9,141.0
186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

CountryID                      float64
Country Name                    object
WEBNAME                         object
Region                          object
World Rank                     float64
Region Rank                    float64
2019 Score                     float64
Property Rights                float64
Judical Effectiveness          float64
Government Integrity           float64
Tax Burden                     float64
Gov't Spending                 float64
Fiscal Health                  float64
Business Freedom               float64
Labor Freedom                  float64
Monetary Freedom               float64
Trade Freedom                  float64
Investment Freedom             float64
Financial Freedom              float64
Tariff Rate (%)                float64
Income Tax Rate (%)            float64
Corporate Tax Rate (%)         float64
Tax Burden % of GDP            float64
Gov't Expenditure % of GDP     float64
Country                         object
Population (Millions)           object
GDP (Billions, PPP)             object
GDP Growth Rate (%)            float64
5 Year GDP Growth Rate (%)     float64
GDP per Capita (PPP)            object
Unemployment (%)                object
Inflation (%)                  float64
FDI Inflow (Millions)           object
Public Debt (% of GDP)         float64
dtype: object

In [13]:
df2 = df.copy()

In [12]:


# df2['Population (Millions)'] = df2['Population (Millions)'].str.replace(r'\D','')
# df2['GDP (Billions, PPP)'] = df2['GDP (Billions, PPP)'].str.replace(r'\D','')
df2

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,71.0,Hong Kong,HongKong,Asia-Pacific,1.0,1.0,90.2,93.3,75.3,83.8,...,Hong Kong SAR,74,4549,3.8,2.8,"$61,393",3.1,1.5,"104,333.0",0.1
1,147.0,Singapore,Singapore,Asia-Pacific,2.0,2.0,89.4,97.4,92.4,95.1,...,Singapore,56,5270,3.6,3.5,"$93,906",2.0,0.6,"62,006.0",110.9
2,120.0,New Zealand,NewZealand,Asia-Pacific,3.0,3.0,84.4,95.0,83.5,96.7,...,New Zealand,48,1886,3.0,3.3,"$38,934",4.9,1.9,"3,572.0",26.4
3,158.0,Switzerland,Switzerland,Europe,4.0,1.0,81.9,85.3,82.0,88.0,...,Switzerland,84,5172,1.1,1.6,"$61,422",4.8,0.5,"40,986.1",42.8
4,7.0,Australia,Australia,Asia-Pacific,5.0,4.0,80.9,79.1,86.5,79.9,...,Australia,248,12465,2.3,2.4,"$50,334",5.6,2.0,"46,368.0",41.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,97.0,Liechtenstein,Liechtenstein,Europe,NaN,NaN,NaN,NaN,NaN,NaN,...,Liechtenstein,38000,612014,NaN,NaN,"$139,100 (2009 est.)",2.1 (2016),NaN,NaN,NaN
183,184.0,Somalia,Somalia,Sub-Saharan Africa,NaN,NaN,NaN,33.7,26.6,7.9,...,Somalia,143,1870,1.8,2.2,NaN,6.0,NaN,384.0,NaN
184,159.0,Syria,Syria,Middle East and North Africa,NaN,NaN,NaN,37.0,24.4,20.3,...,Syria,184,NaN,NaN,NaN,NaN,14.9,NaN,NaN,NaN
185,181.0,Yemen,Yemen,Middle East and North Africa,NaN,NaN,NaN,19.6,22.2,20.3,...,Yemen,300,386,-13.8,-16.1,"$1,287",14.0,4.9,-269.9,141.0
186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN